INSERT INTO BOOKS ( PUBLISH_DATE,  ID, AUTHOR, ISBN, TITLE) VALUES ('2001-01-01',1,'TEST AUTHOR','TEST ISBN','TEST KITAP');
INSERT INTO BOOKS ( PUBLISH_DATE,  ID, AUTHOR, ISBN, TITLE) VALUES ('2001-01-01',2,'TEST AUTHOR2','TEST ISBN2','TEST KITAP2');
INSERT INTO BOOKS ( PUBLISH_DATE,  ID, AUTHOR, ISBN, TITLE) VALUES ('2001-01-01',3,'TEST AUTHOR3','TEST ISBN3','TEST KITAP3');